const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""

global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"


global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/YosafN/SULTAN-KHAN";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029VaXTvQ7JuyAHXjJBs61T";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029VaXTvQ7JuyAHXjJBs61T" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/4c6df8243017a1f7e7890.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923194778990" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923194778990";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923115971525,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://sultan khan-vtsf.onrender.com/";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_07_04_05_05_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTg0LFxuICAgICAgICAxMzAsXG4gICAgICAgIDgxLFxuICAgICAgICA5NSxcbiAgICAgICAgMjI4LFxuICAgICAgICA2MyxcbiAgICAgICAgMjQ3LFxuICAgICAgICAxMzQsXG4gICAgICAgIDIwMixcbiAgICAgICAgMTUyLFxuICAgICAgICA5NCxcbiAgICAgICAgNTMsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTMsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMTc4LFxuICAgICAgICAyNTIsXG4gICAgICAgIDIyLFxuICAgICAgICAxNjMsXG4gICAgICAgIDExMyxcbiAgICAgICAgMjQ2LFxuICAgICAgICAyMDcsXG4gICAgICAgIDEzNixcbiAgICAgICAgMjA4LFxuICAgICAgICAyMSxcbiAgICAgICAgMTIyLFxuICAgICAgICAyNDYsXG4gICAgICAgIDU3LFxuICAgICAgICAyMTMsXG4gICAgICAgIDg0LFxuICAgICAgICA1OCxcbiAgICAgICAgNzRcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTAsXG4gICAgICAgIDM4LFxuICAgICAgICA5OSxcbiAgICAgICAgNTcsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMTIxLFxuICAgICAgICA3MixcbiAgICAgICAgNDgsXG4gICAgICAgIDEyOSxcbiAgICAgICAgNDYsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMjM1LFxuICAgICAgICAxMjAsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTM2LFxuICAgICAgICAyMjksXG4gICAgICAgIDIzOSxcbiAgICAgICAgMjM3LFxuICAgICAgICA1MyxcbiAgICAgICAgNzQsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMzksXG4gICAgICAgIDU1LFxuICAgICAgICAyNDgsXG4gICAgICAgIDE2NyxcbiAgICAgICAgNyxcbiAgICAgICAgODEsXG4gICAgICAgIDE1NixcbiAgICAgICAgMTY1LFxuICAgICAgICA3OSxcbiAgICAgICAgMjI2LFxuICAgICAgICA5MVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDgsXG4gICAgICAgIDYsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMjQ3LFxuICAgICAgICAyMyxcbiAgICAgICAgMjI1LFxuICAgICAgICAyNDksXG4gICAgICAgIDIwMSxcbiAgICAgICAgOTUsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMTYzLFxuICAgICAgICAxMzgsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMjE3LFxuICAgICAgICAxMjIsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTIyLFxuICAgICAgICAyMDEsXG4gICAgICAgIDI0OCxcbiAgICAgICAgNTIsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMTU3LFxuICAgICAgICAxODEsXG4gICAgICAgIDE1OSxcbiAgICAgICAgODYsXG4gICAgICAgIDE4OCxcbiAgICAgICAgODIsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTExLFxuICAgICAgICAyMzgsXG4gICAgICAgIDEwNixcbiAgICAgICAgOTlcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjM0LFxuICAgICAgICA0OCxcbiAgICAgICAgMTUyLFxuICAgICAgICAyMzcsXG4gICAgICAgIDE2LFxuICAgICAgICA5NixcbiAgICAgICAgMTQ1LFxuICAgICAgICAyNDUsXG4gICAgICAgIDExMyxcbiAgICAgICAgMjU1LFxuICAgICAgICA4NixcbiAgICAgICAgNzQsXG4gICAgICAgIDE1MixcbiAgICAgICAgMjUxLFxuICAgICAgICA4MSxcbiAgICAgICAgMTM4LFxuICAgICAgICAxMDQsXG4gICAgICAgIDgzLFxuICAgICAgICAyMDUsXG4gICAgICAgIDIzMyxcbiAgICAgICAgNTAsXG4gICAgICAgIDIyMCxcbiAgICAgICAgODksXG4gICAgICAgIDExNSxcbiAgICAgICAgMTkyLFxuICAgICAgICAxNzAsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMjA2LFxuICAgICAgICAxOTEsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMTc4LFxuICAgICAgICAxMTFcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTk2LFxuICAgICAgICAxODQsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMTI4LFxuICAgICAgICAyMzIsXG4gICAgICAgIDU1LFxuICAgICAgICAyMTgsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMTA2LFxuICAgICAgICAxODgsXG4gICAgICAgIDE5MSxcbiAgICAgICAgNjEsXG4gICAgICAgIDc4LFxuICAgICAgICA5NixcbiAgICAgICAgMjQ0LFxuICAgICAgICAyMzAsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTYyLFxuICAgICAgICAyMjEsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTUyLFxuICAgICAgICAyNTIsXG4gICAgICAgIDE1MixcbiAgICAgICAgMyxcbiAgICAgICAgNzgsXG4gICAgICAgIDI4LFxuICAgICAgICAxODksXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTQwLFxuICAgICAgICAzNCxcbiAgICAgICAgOTNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNTIsXG4gICAgICAgIDEzOSxcbiAgICAgICAgNTUsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMTQxLFxuICAgICAgICAxMCxcbiAgICAgICAgMTYwLFxuICAgICAgICAxOSxcbiAgICAgICAgMTYyLFxuICAgICAgICAyMzEsXG4gICAgICAgIDE4MSxcbiAgICAgICAgNjYsXG4gICAgICAgIDIzMixcbiAgICAgICAgMTM5LFxuICAgICAgICA0NyxcbiAgICAgICAgMjQ2LFxuICAgICAgICAyNCxcbiAgICAgICAgMTMyLFxuICAgICAgICA4OSxcbiAgICAgICAgMjEzLFxuICAgICAgICAxNzAsXG4gICAgICAgIDEzLFxuICAgICAgICAzOCxcbiAgICAgICAgMTQ4LFxuICAgICAgICA2OSxcbiAgICAgICAgNjQsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMTA1LFxuICAgICAgICAxMjEsXG4gICAgICAgIDgxLFxuICAgICAgICAyMDIsXG4gICAgICAgIDhcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTA0LFxuICAgICAgICAgIDEyOSxcbiAgICAgICAgICAyMjAsXG4gICAgICAgICAgMjExLFxuICAgICAgICAgIDc3LFxuICAgICAgICAgIDI1LFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICA3MCxcbiAgICAgICAgICAyMixcbiAgICAgICAgICAxMzQsXG4gICAgICAgICAgMjU0LFxuICAgICAgICAgIDIyMyxcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgMjA5LFxuICAgICAgICAgIDE5MyxcbiAgICAgICAgICAyLFxuICAgICAgICAgIDQyLFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDU4LFxuICAgICAgICAgIDIyMSxcbiAgICAgICAgICAxNTcsXG4gICAgICAgICAgMTY0LFxuICAgICAgICAgIDYwLFxuICAgICAgICAgIDE0NixcbiAgICAgICAgICA2NyxcbiAgICAgICAgICAxMzEsXG4gICAgICAgICAgMjQ2LFxuICAgICAgICAgIDIxNixcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDE4NCxcbiAgICAgICAgICAxMDhcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTIzLFxuICAgICAgICAgIDE1OSxcbiAgICAgICAgICAxNzQsXG4gICAgICAgICAgMjUxLFxuICAgICAgICAgIDc3LFxuICAgICAgICAgIDQxLFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDIyMCxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgNDUsXG4gICAgICAgICAgMTcsXG4gICAgICAgICAgMTgwLFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICAxMDksXG4gICAgICAgICAgMTIxLFxuICAgICAgICAgIDE5OCxcbiAgICAgICAgICAxOTQsXG4gICAgICAgICAgMSxcbiAgICAgICAgICAxODEsXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDE0MyxcbiAgICAgICAgICAxOTUsXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDE2MixcbiAgICAgICAgICAyNCxcbiAgICAgICAgICA2OCxcbiAgICAgICAgICAyMTMsXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgNTcsXG4gICAgICAgICAgMTI1XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMyxcbiAgICAgICAgMjIsXG4gICAgICAgIDgsXG4gICAgICAgIDU2LFxuICAgICAgICAxODUsXG4gICAgICAgIDIzLFxuICAgICAgICAyMixcbiAgICAgICAgODMsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMTMzLFxuICAgICAgICA3MSxcbiAgICAgICAgMTE1LFxuICAgICAgICA0NixcbiAgICAgICAgOTYsXG4gICAgICAgIDg0LFxuICAgICAgICA5OSxcbiAgICAgICAgMTc4LFxuICAgICAgICAyNDksXG4gICAgICAgIDE5OCxcbiAgICAgICAgMjE5LFxuICAgICAgICAyNCxcbiAgICAgICAgMTMsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMTM5LFxuICAgICAgICA3MSxcbiAgICAgICAgMzgsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMjUwLFxuICAgICAgICAzMCxcbiAgICAgICAgMTI1LFxuICAgICAgICAxNDMsXG4gICAgICAgIDM1LFxuICAgICAgICA1MSxcbiAgICAgICAgMjUsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMjQzLFxuICAgICAgICAxNjAsXG4gICAgICAgIDI5LFxuICAgICAgICAyMzgsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTAzLFxuICAgICAgICA2NSxcbiAgICAgICAgMTAsXG4gICAgICAgIDg3LFxuICAgICAgICAxMDIsXG4gICAgICAgIDU1LFxuICAgICAgICAxMzUsXG4gICAgICAgIDY4LFxuICAgICAgICAzLFxuICAgICAgICAxMjYsXG4gICAgICAgIDYwLFxuICAgICAgICAxMDcsXG4gICAgICAgIDI1MixcbiAgICAgICAgNjQsXG4gICAgICAgIDcwLFxuICAgICAgICAxMjQsXG4gICAgICAgIDQ2LFxuICAgICAgICA2MyxcbiAgICAgICAgMjgsXG4gICAgICAgIDIzNyxcbiAgICAgICAgODcsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMTU5LFxuICAgICAgICAxMzVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDIwNCxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJ2V0xKWXpqbzJTV0FNMVFHbGNLbEViWkRya21yTm81V3BlVUEwT0FZWWx3PVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkyMzE5NDc3ODk5MEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiNTZGMzQwNkFFNzNDNTdDMjIyNDEwNTQ1MkNEM0E2MjNcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzE0ODkyNjc3XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTIzMTk0Nzc4OTkwQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIwREJDRjk0RkFBQ0IxRkJDODYxQkE4RjhGNkVBMkUxRFwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MTQ4OTI2NzhcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjMxOTQ3Nzg5OTBAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjU0QjBDMUI1RkM5MDBCQ0VENDA2NkJGNzM0NjM5QjkwXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcxNDg5MjY4MVxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkyMzE5NDc3ODk5MEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiRjlGRjFBREMwNzNBOEU0NkM5RkE0Rjc3QUNERUQwRUZcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzE0ODkyNjgxXG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcInNUcTJzaHJfUnJ5dlJJUjY2UXpycVFcIixcbiAgXCJwaG9uZUlkXCI6IFwiYjQ3NjIzYmYtMDI5NC00NzliLWI1NDQtMzZhY2NhZjEyNzgzXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDEwOCxcbiAgICAgIDc1LFxuICAgICAgNTAsXG4gICAgICAxMzEsXG4gICAgICAxNTEsXG4gICAgICAxMzUsXG4gICAgICAzOSxcbiAgICAgIDU0LFxuICAgICAgMjE5LFxuICAgICAgMjMsXG4gICAgICAxMzIsXG4gICAgICAxNTMsXG4gICAgICA4NixcbiAgICAgIDgyLFxuICAgICAgNjQsXG4gICAgICA2MixcbiAgICAgIDEzLFxuICAgICAgOTMsXG4gICAgICAxNjUsXG4gICAgICAyMjlcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTQ2LFxuICAgICAgMTc4LFxuICAgICAgMzgsXG4gICAgICA2LFxuICAgICAgNzgsXG4gICAgICA0OCxcbiAgICAgIDksXG4gICAgICAyMjEsXG4gICAgICAxNDgsXG4gICAgICAyNDksXG4gICAgICAxNTAsXG4gICAgICAyNTIsXG4gICAgICAyMzIsXG4gICAgICAxNzMsXG4gICAgICA5NCxcbiAgICAgIDAsXG4gICAgICA5MCxcbiAgICAgIDIyNCxcbiAgICAgIDEzNyxcbiAgICAgIDIwOVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCJZQzM5SDI4RVwiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiOTIzMTk0Nzc4OTkwOjZAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcIm5hbWVcIjogXCJzdWx0YW5iYWxvY2hcIixcbiAgICBcImxpZFwiOiBcIjExMDU4Mjk3NTk3MTQwNzo2QGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ1BhUjEvSUZFUC9lM0xFR0dBZ2dBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiUVJQbmJVZDlnd3lVdXcvb3pyc2Y5MmtvMTFyUUdIWVB2ZTNsUytqSnlIaz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJpb2ttVy91NnBLL0wwaEZMaktkWkVKM2JPY1BLUVFVNlBwakMyakxTbm5PeVhsUlkydWdYd2oyc1A3eVBzdlFZeGlxMWJPaWpOMVNjR3NnWkJjNjBDUT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCIxWmNLZDc2M0cxMWNRNitzcVZZSWNUOFNxUDVWWklsZ25iTWQ2b1BLNnM3TUFDeFEzdUNaZVYvT2dEZzE2UFhEeWFrQ2F1YUZValJad01pT2phZ2ppQT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5MjMxOTQ3Nzg5OTA6NkBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDY1LFxuICAgICAgICAgIDE5LFxuICAgICAgICAgIDIzMSxcbiAgICAgICAgICAxMDksXG4gICAgICAgICAgNzEsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDEzMSxcbiAgICAgICAgICAxMixcbiAgICAgICAgICAxNDgsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDIzMixcbiAgICAgICAgICAyMDYsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDMxLFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICAxMDUsXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDkwLFxuICAgICAgICAgIDIwOCxcbiAgICAgICAgICAyNCxcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgMTg5LFxuICAgICAgICAgIDIzNyxcbiAgICAgICAgICAyMjksXG4gICAgICAgICAgNzUsXG4gICAgICAgICAgMjMyLFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgMTIxXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MTQ4OTI2NzQsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFOZkhcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQU5mSC5qc29uIjogIntcImtleURhdGFcIjpcInM2c2FOTHp0dDBWZmJDSGUvS245bnl0RVFoMHVHbXNrb1d3R2JFQitHR0U9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTU4MjY4MDMxMCxcImN1cnJlbnRJbmRleFwiOjcsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzE0ODkyNjAxMzE1XCJ9Igp9" ;


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: YOUSAF KHAN Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.9",
  caption : process.env.CAPTION || "😈Sultan Baloch😈" , // ```『 YOUSAF KHAN BALOCH  』```", //*『YOUSAF • KHAN BALOCH』*\n https://youtube.com/@Y.BGamer110"),
 
  author : process.env.PACK_AUTHER|| "SULTAN BALOCH",
  packname: process.env.PACK_NAME || "❤️",
  botname : process.env.BOT_NAME  || "Sultan Baloch",
  ownername:process.env.OWNER_NAME|| "Sultan Baloch",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "public",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "YOUSAF KHAN",



};

























global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
